apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: build
  namespace: shbose-tenant
spec:
  appModelRepository:
    url: ""
  displayName: build
  gitOpsRepository:
    url: ""
status:
  conditions: null
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    skip-initial-checks: "true"
  creationTimestamp: null
  name: image-controller
  namespace: shbose-tenant
spec:
  application: build
  componentName: image-controller
  containerImage: quay.io/redhat-user-workloads/rhtap-build-tenant/build/image-controller@sha256:87e1515270206d551cd58e13b21cb429fa2da2b91dfb76cb6cc9cba3b3d9af41
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
  source: {}
  targetPort: 8080
status:
  gitops: {}
---
apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  creationTimestamp: null
  name: build-enterprise-contract
  namespace: shbose-tenant
spec:
  application: build
  contexts:
  - description: Application testing
    name: application
  environment:
    name: ""
    type: ""
  resolverRef:
    params:
    - name: url
      value: https://github.com/redhat-appstudio/build-definitions
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/enterprise-contract.yaml
    resolver: git
status:
  conditions: null
